-- GLOWMAISON STORE - SUPABASE DATABASE SETUP
-- Jalankan file ini di Supabase SQL Editor.

drop table if exists public.products cascade;

create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  description text,
  image_url text,
  old_price integer default 0,
  price integer not null default 0,
  badge text,
  stock integer default 0,
  created_at timestamp with time zone default now()
);

alter table public.products enable row level security;

create policy "Public can read products"
on public.products
for select
to anon, authenticated
using (true);

create policy "Authenticated can insert products"
on public.products
for insert
to authenticated
with check (true);

create policy "Authenticated can update products"
on public.products
for update
to authenticated
using (true)
with check (true);

create policy "Authenticated can delete products"
on public.products
for delete
to authenticated
using (true);

insert into public.products
(name, category, description, image_url, old_price, price, badge, stock)
values
(
  'Hydra Glow Serum',
  'Serum',
  'Serum ringan untuk membantu kulit tampak lembap dan glowing.',
  'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=700&q=80',
  299000,
  199000,
  'Best Seller',
  25
),
(
  'Daily Repair Cream',
  'Moisturizer',
  'Moisturizer premium untuk menjaga skin barrier tetap sehat.',
  'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&w=700&q=80',
  349000,
  249000,
  'Diskon',
  18
),
(
  'Luxury Cleansing Gel',
  'Cleanser',
  'Pembersih wajah lembut untuk pemakaian harian.',
  'https://images.unsplash.com/photo-1612817288484-6f916006741a?auto=format&fit=crop&w=700&q=80',
  229000,
  159000,
  'New',
  30
);

-- STORAGE POLICIES
-- Buat bucket manual dulu:
-- Storage -> New bucket -> name: products
-- Centang Public bucket jika tersedia.
-- Jika policy duplicate error, hapus policy lama dulu dari Storage -> Policies.

create policy "Public can read product images"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'products');

create policy "Authenticated can upload product images"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'products');

create policy "Authenticated can update product images"
on storage.objects
for update
to authenticated
using (bucket_id = 'products')
with check (bucket_id = 'products');

create policy "Authenticated can delete product images"
on storage.objects
for delete
to authenticated
using (bucket_id = 'products');
